#!/usr/bin/env swift
// Embeds the built web UI (Web/dist) into the WebAssets target, so the app is one binary with
// nothing beside it to lose.
//
//   cd Web && npm run build && cd .. && swift Tools/Release/embed-web.swift
//
// Files go in as base64 string literals: the compiler handles a long string far faster than an
// array of bytes.

import Foundation

let root = URL(filePath: #filePath).deletingLastPathComponent().deletingLastPathComponent().deletingLastPathComponent()
let dist = root.appending(path: "Web/dist")
let output = root.appending(path: "Packages/CrawlspaceKit/Sources/WebAssets/Generated.swift")

let types = [
    "html": "text/html; charset=utf-8", "js": "text/javascript; charset=utf-8", "css": "text/css; charset=utf-8",
    "svg": "image/svg+xml", "png": "image/png", "ico": "image/x-icon", "woff2": "font/woff2", "json": "application/json",
    "txt": "text/plain; charset=utf-8", "webmanifest": "application/manifest+json",
]

guard let enumerator = FileManager.default.enumerator(at: dist, includingPropertiesForKeys: [.isRegularFileKey]) else {
    FileHandle.standardError.write(Data("No Web/dist. Run `npm run build` in Web/ first.\n".utf8))
    exit(1)
}

var entries: [String] = []
var total = 0
for case let file as URL in enumerator {
    guard (try? file.resourceValues(forKeys: [.isRegularFileKey]).isRegularFile) == true else { continue }
    let path = String(file.standardizedFileURL.path.dropFirst(dist.standardizedFileURL.path.count + 1))
    let data = try Data(contentsOf: file)
    total += data.count
    let type = types[file.pathExtension.lowercased()] ?? "application/octet-stream"
    entries.append("        (\"\(path)\", \"\(type)\", \"\(data.base64EncodedString())\"),")
}
guard entries.contains(where: { $0.contains("\"index.html\"") }) else {
    FileHandle.standardError.write(Data("Web/dist has no index.html.\n".utf8))
    exit(1)
}

let source = """
// Generated by Tools/Release/embed-web.swift from Web/dist. Don't edit by hand.

enum Generated {
    static let files: [(path: String, contentType: String, base64: String)] = [
\(entries.sorted().joined(separator: "\n"))
    ]
}

"""
try source.write(to: output, atomically: true, encoding: .utf8)
print("Embedded \(entries.count) files (\(total / 1024) KB) into \(output.path)")
