// Generated by Tools/Release/embed-web.swift from Web/dist. Don't edit by hand.
// This committed copy is a placeholder; release builds replace it with the real UI.

enum Generated {
    static let files: [(path: String, contentType: String, base64: String)] = [
        ("index.html", "text/html; charset=utf-8", "PCFkb2N0eXBlIGh0bWw+PGh0bWw+PGhlYWQ+PG1ldGEgY2hhcnNldD0idXRmLTgiPjx0aXRsZT5DcmF3bHNwYWNlPC90aXRsZT48L2hlYWQ+Cjxib2R5IHN0eWxlPSJmb250LWZhbWlseTotYXBwbGUtc3lzdGVtLHNhbnMtc2VyaWY7cGFkZGluZzozcmVtO2NvbG9yOiMzMzMiPgo8aDE+Q3Jhd2xzcGFjZTwvaDE+PHA+VGhlIHdlYiBVSSBoYXNuJ3QgYmVlbiBidWlsdCBpbnRvIHRoaXMgY29weS4gUnVuIDxjb2RlPm5wbSBydW4gYnVpbGQ8L2NvZGU+IGluIDxjb2RlPldlYi88L2NvZGU+LAp0aGVuIDxjb2RlPnN3aWZ0IFRvb2xzL1JlbGVhc2UvZW1iZWQtd2ViLnN3aWZ0PC9jb2RlPiwgb3IgdXNlIDxjb2RlPmNyYXdsc3BhY2Ugc2VydmUgLS1kZXY8L2NvZGU+IHdpdGggdGhlIFZpdGUgZGV2IHNlcnZlci48L3A+CjwvYm9keT48L2h0bWw+"),
    ]
}
